#ifndef OPENSSL_OPENSSLCONF_H
#define OPENSSL_OPENSSLCONF_H

/* Platform */
#define OPENSSL_THREADS
#define OPENSSL_NO_ASYNC
#define OPENSSL_NO_DYNAMIC_ENGINE
#define OPENSSL_NO_POSIX_IO
#define OPENSSL_NO_SSL3
#define OPENSSL_NO_SSL3_METHOD
#define OPENSSL_NO_EC_NISTP_64_GCC_128
#define OPENSSL_USE_NODELETE
#define OPENSSL_PIC

/* Algorithms */
#define OPENSSL_NO_IDEA
#define OPENSSL_NO_MDC2
#define OPENSSL_NO_RC5
#define OPENSSL_NO_SEED
#define OPENSSL_NO_SM2
#define OPENSSL_NO_SM3
#define OPENSSL_NO_SM4

/* API */
#define OPENSSL_API_COMPAT 0x10100000L

#endif
